# Set the default model config to clip,
# which adds special preprocessers to dataset_config.
includes:
- models/clip.yaml

dataset_config:
  news_clippings:
    # By default data_dir is ~/.cache/torch/mmf/data
    # An absolute path can be defined with a backslash
    data_dir: ${env.data_dir}/datasets
    option: ${env:split}
    annotations:
      train:
      - news_clippings/data/${env:split}/train.json
      val:
      - news_clippings/data/${env:split}/val.json
      test:
      - news_clippings/data/${env:split}/test.json
    images:
      train:
      - visual_news/origin
      val:
      - visual_news/origin
      test:
      - visual_news/origin

# Typically one Nvidia GPU with 12212MiB
# can handle a batch size of 16
training:
  seed: 2
  batch_size: 16
  max_updates: ${scheduler.params.num_training_steps}
  # Use wandb logging. Please see for more info
  # in website/docs/notes/logging.md under the main MMF repo
  # tensorboard: false
  # wandb: 
  #   enabled: true
  #   wandb_projectname: ${env:wandb_projectname}
  #   wandb_runname: ${env:split}_${env:model}